# Generated by Django 3.0.2 on 2020-01-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=2002)),
                ('article_id', models.IntegerField(default=0)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=250)),
            ],
        ),
    ]
