# Generated by Django 3.0.2 on 2020-01-19 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
